export default {
  primaryBackground: 'darkGray',
  offsetBackground: 'darkMediumGray',
  activeBackground: 'mediumGray',
  offsetFont: 'lightGray',
  primaryFont: 'white',
  white: 'white',
  pink: 'pink',
  blue: 'blue',
  green: 'green',
  yellow: 'yellow',
  red: 'red',
  teal: 'teal',
  purple: 'purple',
  darkBlue: 'darkBlue',
  orange: 'orange',
  darkGray: 'darkGray',
};
