export default {
  primaryBackground: 'white',
  offsetBackground: 'offWhite',
  activeBackground: 'mediumWhite',
  offsetFont: 'lightGray',
  primaryFont: 'darkGray',
  white: 'white',
  pink: 'pink',
  blue: 'blue',
  green: 'green',
  yellow: 'yellow',
  red: 'red',
  teal: 'teal',
  purple: 'purple',
  darkBlue: 'darkBlue',
  orange: 'orange',
  darkGray: 'darkGray',
};
